=encoding utf8

=head1 NAME

Facebook::Cookbook - How to cook your face.....book :)

=head1 DESCRIPTION

The L<Facebook cookbook|Facebook::Cookbook> is a series of recipes showing various L<Facebook> features. Most recipes present some 
code demonstrating some feature, and then explain the details of the code.

You should probably read the L<Facebook::Manual> first. The manual explains Facebook concepts without being too code-heavy.

=head1 RECIPES

=head2 Web Applications

=head2 Desktop Applications

=head1 SUPPORT

IRC

  Join #facebook on irc.perl.org.

Repository

  http://github.com/Getty/p5-facebook
  Pull request and additional contributors are welcome
 
Issue Tracker

  http://github.com/Getty/p5-facebook/issues

=head1 AUTHOR

Torsten Raudssus <torsten@raudssus.de> http://www.raudssus.de/

=head1 CONTRIBUTORS

Your name could be here.

=head1 COPYRIGHT

Copyright (c) 2010 the Facebook L</AUTHOR> and L</CONTRIBUTORS> as
listed on L<Facebook> and all other packages in this distribution.

=head1 LICENSE

This documentation is free software and may be distributed under the same terms
as perl itself.

=cut
